# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       libxcb

# >> macros
# << macros

Summary:    A C binding to the X11 protocol
Version:    1.10
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://xcb.freedesktop.org/
Source0:    http://xcb.freedesktop.org/dist/%{name}-%{version}.tar.bz2
Source100:  libxcb.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(python2)
BuildRequires:  pkgconfig(pthread-stubs)
BuildRequires:  pkgconfig(xcb-proto) >= 1.7
BuildRequires:  pkgconfig(xau) >= 0.99.2
BuildRequires:  libxslt

%description
Description: %{summary}

%package doc
Summary:    Documentation for %{name}
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
Description: %{summary}

%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   libpthread-stubs
Requires:   libXau-devel

%description devel
Description: %{summary}

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --docdir=%{_datadir}/doc/%{name}-%{version} \
    --disable-build-docs

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post

# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/*.so.*
# << files

%files doc
%defattr(-,root,root,-)
# >> files doc
%{_datadir}/doc/%{name}-%{version}
%{_mandir}/man3/*
# << files doc

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/xcb
%{_libdir}/*.so
%{_libdir}/pkgconfig/*.pc
# << files devel
