# 
# Do not Edit! Generated by:
# spectacle version 0.18
# 
# >> macros
# << macros

Name:       libxcb
Summary:    A C binding to the X11 protocol
Version:    1.7
Release:    0
Group:      System/Libraries
License:    MIT
URL:        http://xcb.freedesktop.org/
Source0:    http://xcb.freedesktop.org/dist/%{name}-%{version}.tar.bz2
Source100:  libxcb.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(xorg-macros)
BuildRequires:  pkgconfig(pthread-stubs)
BuildRequires:  pkgconfig(xcb-proto)
BuildRequires:  pkgconfig(xau)
BuildRequires:  pkgconfig(xproto)
BuildRequires:  libxslt
BuildRequires:  python-devel


%description
Description: %{summary}


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   libpthread-stubs
Requires:   libXau-devel

%description devel
Description: %{summary}

%package doc
Summary:    Documentation for %{name}
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
Description: %{summary}


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --docdir=%{_datadir}/doc/%{name}-%{version} \
    --disable-build-docs

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install 

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig








%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/*.so.*
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/xcb
%{_libdir}/*.so
%{_libdir}/pkgconfig/*.pc
# << files devel

%files doc
%defattr(-,root,root,-)
# >> files doc
%{_datadir}/doc/%{name}-%{version}
# << files doc

